### ISSUE TITLE
Wrong HTML comments

### ISSUE THREAD

**Issue by rowild** [Digitalbrainstem/ejs-grammar#22]
Hitting sth like CTRL - Slash on order to comment out a HTML passage generates 2 slashes instead of 

I don't know if this intended behaviour or a bug. Maybe someone could clarify...

BTW: Is this extension still in development?

**Comment by Betanu701** [comment]
@rowild Thanks for the issue. The extension is still under development, I just have not had time to learn/work on the other components that are needed to get more features. Basically I need to learn how to create the language server, and hopefully pull in the built in languages so I don't have to rewrite the entire libraries. 

As far as your issue goes, this could be due to the fact that ejs is mostly javascript with html sugar, so the "comment out" would go to double slash by default.  When I initial wrote the plugin, it relied on regex but could only read line by line. It was difficult just to get the ejs tags to read on a seperate line. I do not know if the key bindings for line level comment allow for 2 separate languages as well.

**Comment by Betanu701** [comment]
@rowild If you are up to the task, you can see if there is a way for having 2 seperate language line level comments for key bindings.

**Comment by rowild** [comment]
@Betanu701 Thank you for your detailed answer and the hints, where to look for the solution! Currently I am not up to the task, but I intend to dig into VSCode extension programming soon. It seems just to be too important to ignore. 
Let's keep this issue open, please, if that is all right with you, and come back to it later.

Thanks again! Good luck with your work!

**Comment by Betanu701** [comment]
@rowild I have no problem keeping this open. If you want to get into VSCode extensions, you are more than welcome to help out on this one, when you find the time. I included all my resources and howtos in the readme of the extension.
