### ISSUE TITLE
Blank space being added when jumping to the next line 

### ISSUE THREAD

**Issue by olivierkaisin** [Digitalbrainstem/ejs-grammar#6]
Hi there!

First of all, thanks for the awesome work. This is definitely the best .ejs extension for VSCode so far!

I noticed a weird behaviour with indentation. 
Consider the following ejs code:

```ejs
<div class="test">
  <% if (variable) { %> 
  <% } %>
</div>
```

If I place the typing cursor just before the `<% } %>` and press <enter>. It jumps to the next line but also adds a space before the `<% } %>`.

**Before:**
![before](https://gmkr.io/s/5a71ce682cbe58564e49903c/0)

**After:**
![after](https://gmkr.io/s/5a71ce81292f6859685c5823/0)

Not sure what causes this, but I didn't experience that issue with the other .ejs extension made by Qassim Farid.

Let me know if I can be of any help.

**Comment by Betanu701** [comment]
I was not able to get it to jump with your exact repo steps; however, I was able to get it to happen when I removed the new line then hit return. This is caused by the indentation rules in language-configuration.json 

I went ahead and removed the regex portion that was causing this. `{(?!.+}).*`

Let me know if this fixes your issue or not. I published the new version on VSCode So you should just need to update the extension.

**Comment by Betanu701** [comment]
Closing due to no response. If this issue is still valid please reopen.
