### ISSUE TITLE
Feature Request: Add syntax support to .ejs.js extension

### ISSUE THREAD

**Issue by omar84** [Digitalbrainstem/ejs-grammar#9]
Feature Request: Add syntax support to .ejs.js extension

**Comment by Betanu701** [comment]
I will add this to the todo. Is there anything in particular that is supposed to happen in raw .ejs.js files? From my understanding, this would just be a standard javascript file. Maybe there are certain features or snippets you want to show up?

**Comment by omar84** [comment]
In ejs, you have <% yourVariable %> and <%= yourVariable  %> to load variables into the template.

right now this is being registered as a syntax error, where as it should be understood that it is valid ejs.

**Comment by meesfrensel** [comment]
I don't think this should be added, since `.ejs.js` isn't exactly a standard ejs file extension and looks more like a general Javascript file. Maybe it's a better idea to support custom file extensions/types through user settings?

**Comment by Betanu701** [comment]
I am not sure if .ejs.js would be a standard or not. I don't think we can have "standard" javascript files with the use of ejs. If I am wrong, please correct me and when can look into adding this. 

.rhtml has been removed thanks to @meesfrensel as of version 0.3.0
rhtml was in there originally because I was using that as a template to get this repo up and going. It had a lot of similarities in the language that allowed me to find how to add the language support. The actual language file though was completely written by me, as there was a lot of erroneous stuff that I did not need.

**Comment by ExE-Boss** [comment]
You can already do this by setting:
```json
"files.associations": {
	"*.ejs.js": "ejs",
}
```
in **VS&nbsp;Code**’s `settings.json`.
