### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by bombillazo** [Digitalbrainstem/ejs-grammar#90]
I dont see any recent activity, plus various pending PRs that don't get merged. Is there still worth contributing here or is there an active alternative to use `ejs` files in VS Code?

**Comment by Betanu701** [comment]
I am still around, I need to go through the pull request and see what they are adding. Is there something you wanted to add?

**Comment by bombillazo** [comment]
Hey, thanks for the super quick response. Im trying to find an extension that can format ejs files, mainly like prettier does or some type of plugin.

**Comment by Betanu701** [comment]
The last time I looked into that, it would require to build a "server" function into the extension. I wanted to be able to use the built in HTML one, but I could never get it working correctly. 

To be fair, the last time I looked into this was ~2.5 years ago. VSCode may have made it easier to use a base language for its Grammer server. 

If it has not, we would need to build a Grammer server that will essentially add functionality to reformat the entire thing. I thought about pulling the HTML one and using it, but it was going to be too much work for me at the time. I also did not want to slow down the extension because it would have to parse every so often to get it to format correctly. 

If you know a way to do it/have suggestions, I am all open to it.

**Comment by Betanu701** [comment]
On the same note, my not so smooth workaround, was to switch it to HTML briefly, format it then switch it back to ejs... Not great, but it worked, mostly

**Comment by bombillazo** [comment]
Ok got it, so it is not that trivial. :S Yeah Im not sure what to suggest given that sure, EJS is heavily based on HTML but hacking on top of the HTML server could be more difficult...

I think defining the key features an EJS formatted does will help understand the scope and work required. 

I was thinking mostly just basic indentation, syntax highlighting, and proper management of partial template files (this is a big one)
